### ISSUE TITLE
sspdlog问题

### ISSUE THREAD

**Issue by jasonleecode** [oyoungs/SoundManager#1]
编译过程中提示“wavstream.cc:6:29: fatal error: sspdlog/sspdlog.h: No such file or directory”,请问这个是什么库？是你自己修改的spdlog库吗？我安装sdplog后依然没有解决这个问题，后来看wavstream.cc的源码发现代码中没有调用这个库的函数，所以注释掉这个头文件，再编译就OK了。

**Comment by oyoungs** [comment]
去掉那个包含就行了， 我自己调试的时候加的， 调试完了只去掉了使用的地方，忘了去掉头文件的包含
